# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5e242dc3ada23c7854ee358881b9f13096bedf9ec6f2b6ef5c9937fd1676c6ee31058b043b35ae5c0798ccf8c0ed9ba69fad71f61a60e089d9d8d7491e567fd2

test:
  secret_key_base: b723e5c1a2769135c53a7e54f889d73edc05380eabffcae836e49bd8924e4c812296736a4d8d52c26641d0689a1b580adc4664b0325af4a00470533cf5681cfd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
